### ISSUE TITLE
Name and logo wanted

### ISSUE THREAD

**Issue by funkyfuture** [funkyfuture/delb#1]
i'm not particularly fond of the library's name. there's no need to include 'lxml' because the api is intended to be sufficient on itself and the high-performance backend may be exchanged at some point. regarding the 'domesque' part i'm not sure whether it requires certain cultural knowledge to understand the nuance.

a project's logo should communicate the what-is-is as well. actually a straight-forward idea for it would be a tree around which a snake is winding. there could be (two different) fruits of knowledge on that tree. admittedly this has a strong reference to the culture of abrahamic religions.

you're welcome to share your ideas and feedback on those. if you like drawing, why not give it a try?

**Comment by 03b8** [comment]
That's a nice and simple logo idea. Here's a rough sketch of how I've imagined it: <br/>
<img src="https://i.imgur.com/N0fPPAe.png" width="100px"/>
A matching library name could be something like _treesnake_, [_morelia_](https://en.wikipedia.org/wiki/Morelia_(snake)), _DOMrelia_ etc.

**Comment by funkyfuture** [comment]
some thoughts:

- i'm surprised i like the greenish theme

----

- the snake however could be more pythonic - blue and yellow
- ergo red would be available for the (dangerous) fruits, black for branches
- maybe i'll try a Kandinsky imitation

----

- a few asymetric subbranches would better represent a document

----

- i don't know whether this is practical, but if css could be used, it should be possible to have the colors adapt to a dark or light background from one source with filters, shoudn't it?

----

- `minima-morelia` as name?
  - easily pronouncable
  - does the categorization as minimal apply as the api provides the least parts one needs to work with a distinguished subset of xml documents - text documents?
  - i wonder what @zed-g laughs out about the pun
  - should be memoizable for people with relations to the humanities, okay it's eurocentric

----

- i'm very unsure whether and how `dom` should be part of the name. there's no promise to fully comply with a DOM spec.

----

- i certainly will put the intersection of the trunk and the crown's outline to a golden ration

----

@03b8 can you provide a svg file that your proposal was rendered from?

**Comment by 03b8** [comment]
`minima-morelia` – love it! :smile:

**Comment by funkyfuture** [comment]
~~meanwhile i think `morelia` is just fine (also given that there may come repos with name suffixes `-py`, `-rs` and `-js`). @03b8 would you make the adjustments in the repo content, so we can add you to an `AUTHORS.rst`?~~

oh no, there's already a [morelia on the PyPI](https://pypi.org/project/morelia/). more tea to drink.

**Comment by 03b8** [comment]
`morelia` would have been nice, `minima-morelia` is kinda long, but what about `minimorelia`? it's short, catchy, retains the pun/reference and is (to my knowledge) not used yet.

**Comment by funkyfuture** [comment]
> but what about `minimorelia`

nah, i don't find it really catchy and i'd expect myself to mistype it a lot (`m/n` and `i/o` residing so close to each other on keyboards).

from the Morelia species [viridis](https://en.wikipedia.org/wiki/Green_tree_python) would have my sympathies, [but …](https://pypi.org/project/viridis/)

**Comment by funkyfuture** [comment]
sundayafternoonthought: given it's the tenth year of its appearance; why not `delb` as acronym for ["dónde està la biblioteca?"](https://www.youtube.com/watch?v=j25tkxg5Vws)?

**Comment by 03b8** [comment]
I agree with your criticism regarding the typo risk. "delb" is a great idea, I like it a lot :) Let's go with that.

**Comment by SDR0512** [comment]
![9ea5654b-93e7-4d55-9e83-4f28cd6188a6_200x200](https://user-images.githubusercontent.com/58349712/86606394-8e97d880-bfc5-11ea-8e4c-7fff6b57535a.png)

**Comment by SDR0512** [comment]
![daf7789a-4f1d-47b4-b5a1-06d0410c5282_200x200](https://user-images.githubusercontent.com/58349712/86606911-3b725580-bfc6-11ea-88d0-5a57b9b74fdc.png)
