### ISSUE TITLE
Create a GH workflow for releases

### ISSUE THREAD

**Issue by funkyfuture** [funkyfuture/delb#35]
TODO add specs

**Comment by JKatzwinkel** [comment]
Would you use a `git push --tags`-triggered workflow similar to what's proposed in https://github.com/funkyfuture/delb/commit/1588129a7f4af87a25f7f2f0d5e043e83332d15c, or rather one of those things which you trigger manually via API? Either way, I've never done this and suspect we will be creating a lot of throwaway forks in the process...

**Comment by funkyfuture** [comment]
i'm almost through with establishing it for deck-chores and it doesn't motivate me to repeat this here. for that project it clearly solves problems that are worth the effort. harly here.

so yes, let's keep all flows centered around a `Makefile`.
